print("Hello World")
print("Ammad")
print("Ammad Rana")
print("Hi! I am Ammad.")
print("25")
print(2*2)
print("2+5+9")
print(5,"+",4,"=",5+4)
print("Hello, ","I ","am ","Ammad. ")
print("Ammad ","is ","20 ","years ","old. ")
