print("Hello World")
print("Hamna")
print("hamna islam")
print("Hi! I am hamna.")
print("25")
print(2*2)
print("2+5+9")
print(5,"+",4,"=",5+4)
print("Hello, ","I ","am ","hamna. ")
print("hamna","is ","20 ","years ","old. ")
