print("Hello World")
print("HAMNA")
print("HAMNA ISLAM")
print("Hi! I am Hamna.")
print("25")
print(2*2)
print("2+5+9")
print(5,"+",4,"=",5+4)
print("Hello, ","I ","am ","Hamna. ")
print("HAMNA ","is ","19 ","years ","old. ")
